`<RecruitCard />`
SSAF-SOUND/ssaf-sound-fe pull request #119
Opened 2023-07-17 11:23 UTC by otterp012

## Issues

- #87 

## 구분

- [ ] 버그 수정
- [x] 기능 추가
- [ ] 코드 리팩터링
- [ ] 문서 업데이트
- [ ] 기타

## 주요 변경점

- 리쿠르트 카드 및 작은 리쿠르트 카드 컴포넌트를 추가했습니다.

## 스크린샷

## 기타

2023-07-17 11:26 UTC, otterp012 commented on src/components/Common/Avatar/SingleAvatar.tsx
> +
기존에 사용하던 컴포넌트와 충돌없도록, 일단은 위처럼 해놨어요!

2023-07-17 11:39 UTC, otterp012 commented on src/components/Dday/index.tsx
> +  } = props;
기본값들은 다음 PR에서 정리해서 올릴게요!

2023-07-17 11:40 UTC, otterp012 commented on src/components/RecruitCard/Small/index.tsx
> +    lineHeight: '22px',
`lineHeight`는 임의로 조정했어요 의도하신 디자인으로 맞추기 위해서!

2023-07-17 20:38 UTC, mjsdo requested changes
일단 두가지 이유로 approve를 못했는데

1. `lineClamp`가 `re-export`되지 않았는데, `utils`에서 가져오고 있어서 오류가 발생합니다. (에디터상에서도 오류가 떠요)
   - PR 올리기 전에 스토리북 배포 혹은 개발모드에서 실행한 뒤 오류 한번만 체크하고 올려주시면 감사하겠습니다.

2. [유저정보 PR](https://github.com/SSAF-SOUND/ssaf-sound-fe/pull/111)에서 한번 언급드리긴 했는데, 
스토리북 페이지 추가하는데 모듈 버그가 발생해서 제가 스토리북을 7.0.27로 업데이트했고, 
이거 동기화하려면 제꺼 머지된거에서 yarn 실행하신 다음에 버전을 맞춰야할거에요. 

이 PR에 package.json에는 7.0.8로 명시되어있어서 머지 잘못되면 다운그레이드 될 것 같아요. 
한번 체크하고 다시 올려주시면 감사하겠습니다.

2023-07-18 06:28 UTC, otterp012 commented on src/components/RecruitCard/Wide/index.tsx
> +      <div css={flex('', '', 'column', 5)}>
거기 아바타 부분이 스크롤되니까,, 데스크탑버전에서 너무 사용성이 안좋더라구요
그래서 최대 길이가 나와도 카드 컴포넌트에서 스크롤 없도록 임의로 줄여놨는데! 해당 부분은 이야기 해봐야할 것 같아요

2023-07-18 06:36 UTC, otterp012 commented on src/components/RecruitCard/Wide/index.tsx
> +}
저렇게 해둔 이유는 {...rest} 이런 처리를 선호하기 때문에 해둔거에요!
근데 콜라가 이전에 작성하신 컴포넌트와 구조를 통일하기 위해서는 콜라처럼 수정해도 괜찮을 것 같아요!
여기는 꼭 데이터가 필요한 부분이기도 하구요

2023-07-18 06:43 UTC, otterp012 commented on src/components/RecruitCard/Wide/RecruitTitle.tsx
> +  },
수정했어요!

2023-07-18 07:46 UTC, closed without merging

2023-07-18 09:12 UTC, mjsdo commented on src/components/RecruitCard/Wide/index.tsx
> +}
개인적으로, 그룹화가 가능한 객체들은, 하나의 프로퍼티로 그룹화 해주는게 더 좋다고 생각해요. (마치 함수의 인자를 전달할 때, 플랫하게 펼치는게 아닌, 객체로 그룹화해서 전달하는 것 처럼!)

리쿠르팅 카드에서 자체적으로 만들어낸 컨텍스트가 있고, 그 컨텍스트에 주입해줄 프로퍼티였다면 어떤 방식으로 하든 상관없겠지만,
이 컴포넌트는 API 응답 메세지 타입에 종속적이다 보니까,
어디까지가 컴포넌트를 그리는데 핵심적인 데이터인지, 어디까지가 옵션인지가 명확해야 한다고 생각해서요!